import { NextResponse } from "next/server";
import groq from "@/lib/groq";
import { Document, Packer, Paragraph, TextRun, HeadingLevel } from "docx";

// --- HELPER: GENERATE WORD DOC ---
async function generateWordDoc(topic, content) {
  const cleanContent = content.replace(/\*\*/g, "").replace(/#/g, "").split("\n");

  const children = [
    new Paragraph({
      text: `DOKUMEN: ${topic.toUpperCase()}`,
      heading: HeadingLevel.HEADING_1,
    }),
    new Paragraph({ text: "" }),
  ];

  cleanContent.forEach(line => {
    if (line.trim()) {
      children.push(new Paragraph({
        children: [new TextRun({ text: line, size: 24 })], // 12pt font
      }));
      children.push(new Paragraph({ text: "" }));
    }
  });

  children.push(new Paragraph({
    text: `Generated by Synapse Node-01 at ${new Date().toLocaleString()}`,
    style: "IntenseQuote",
  }));

  const doc = new Document({ sections: [{ children }] });
  const buffer = await Packer.toBuffer(doc);
  return buffer.toString("base64");
}

// --- MAIN ORCHESTRATOR ---
export async function POST(req) {
  try {
    const body = await req.json().catch(() => null);
    if (!body || (!body.message && !body.image)) {
      return NextResponse.json({ error: "Invalid input provided." }, { status: 400 });
    }

    const { message, history, image } = body;

    let finalResponse = "";
    let fileData = null;
    let activeAgent = "General Assistant";

    // --- 1. VISION AGENT ---
    if (image) {
      activeAgent = "Synapse Vision Core";
      const visionCompletion = await groq.chat.completions.create({
        messages: [
          {
            role: "user",
            content: [
              { type: "text", text: message || "Analisis gambar ini." },
              { type: "image_url", image_url: { url: image } }
            ],
          },
        ],
        model: "llama-3.2-11b-vision-preview", // Model Vision Aktif
        temperature: 0.2,
      });
      return NextResponse.json({ response: visionCompletion.choices[0]?.message?.content, agent: activeAgent });
    }

    // --- 2. ROUTER AGENT (INI YANG RUSAK SEBELUMNYA) ---
    const routerPrompt = `
      CONTEXT: User is chatting with an AI Enterprise.
      LAST MESSAGE: "${message}"
      
      Classify intent:
      - DOC_REQ: User asks to CREATE or REVISE a document, report, proposal, file, or surat.
      - ANALYST_REQ: User asks to analyze data/logs.
      - CHAT: General conversation.
      
      Respond ONLY with category name.
    `;

    // [FIXED] Menggunakan Model Aktif
    const routerCompletion = await groq.chat.completions.create({
      messages: [{ role: "user", content: routerPrompt }],
      model: "llama-3.1-8b-instant",
    });

    const intent = routerCompletion.choices[0]?.message?.content?.trim();
    const conversationHistory = Array.isArray(history)
      ? history.map(msg => ({ role: msg.role === 'user' ? 'user' : 'assistant', content: msg.content })).slice(-6)
      : [];

    // --- 3. EKSEKUSI ---
    if (intent === "DOC_REQ") {
      activeAgent = "Document Writer Agent";

      const docPrompt = `
        You are a Professional Document Writer.
        Based on: "${message}",
        Generate the FULL CONTENT of the document directly.
        Do not talk. Just write the body content.
      `;

      const docCompletion = await groq.chat.completions.create({
        messages: [...conversationHistory, { role: "user", content: docPrompt }],
        model: "llama-3.3-70b-versatile",
      });

      const content = docCompletion.choices[0]?.message?.content;
      const base64File = await generateWordDoc("Dokumen Synapse", content);

      finalResponse = `✅ **Dokumen Berhasil Disusun.**\n\nSaya telah membuat file dokumen sesuai instruksi Anda. Silakan unduh melalui kartu di bawah ini.\n\n*Pratinjau:*\n> ${content.substring(0, 100).replace(/\n/g, " ")}...`;

      fileData = {
        name: `Synapse_Doc_${Date.now().toString().slice(-4)}.docx`,
        type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        content: base64File
      };

    } else if (intent === "ANALYST_REQ") {
      activeAgent = "Data Analyst Agent";
      const analystCompletion = await groq.chat.completions.create({
        messages: [...conversationHistory, { role: "user", content: `Analyze rigorously: "${message}"` }],
        model: "llama-3.3-70b-versatile",
      });
      finalResponse = analystCompletion.choices[0]?.message?.content;
    } else {
      activeAgent = "Chat Assistant";
      const chatCompletion = await groq.chat.completions.create({
        messages: [{ role: "system", content: "Professional Assistant." }, ...conversationHistory, { role: "user", content: message }],
        model: "llama-3.3-70b-versatile",
      });
      finalResponse = chatCompletion.choices[0]?.message?.content;
    }

    return NextResponse.json({
      response: finalResponse,
      generatedFile: fileData,
      agent: activeAgent
    });

  } catch (error) {
    console.error("Synapse System Failure:", error);
    return NextResponse.json({ error: "Internal Error" }, { status: 500 });
  }
}
